---
version: '2'

networks:
  spotweb:

volumes:
  mysql_datavolume:
  spotweb_datavolume:

services:
  spotweb_db:
    image: isuftin/spotweb_db:1.3.1-2
    build:
      context: ./spotweb_db
    hostname: spotweb_db
    networks:
      spotweb:
        aliases:
          - spotweb_db
    volumes:
      - mysql_datavolume:/var/lib/mysql
    restart: always

  spotweb_server:
    image: isuftin/spotweb:1.3.1-2
    build:
      context: ./spotweb_server
    links:
      - spotweb_db
    ports:
      - "80:80"
    networks:
      spotweb:
        aliases:
          - spotweb_server
    restart: always
    command: dockerize -wait tcp://spotweb_db:3306 -timeout 60s /bin/bash -c "cron && source /etc/apache2/envvars && rm -f /var/run/apache2/apache2.pid && apachectl -k restart -DFOREGROUND | true"
    volumes:
      - spotweb_datavolume:/var/www/spotweb
    depends_on:
      - spotweb_db
